server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info,prometheus
      base-path: /_
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
    metrics:
      enabled: true
    info:
      enabled: true
  metrics:
    distribution:
      slo:
        jvm.gc: 10ms, 20ms, 30ms, 50ms, 100ms, 150ms, 250ms, 500ms, 1s
      percentiles-histogram:
        all: true
  prometheus:
    metrics:
      export:
        enabled: true

spring:
  application:
    name: backend-test

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

---
spring:
  config:
    activate:
      on-profile: local

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  packages-to-scan: com.wallapop.marsRover